# Generated by Django 2.0.2 on 2018-03-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('bangumi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=1, max_digits=2)),
                ('count', models.IntegerField()),
                ('cover', models.CharField(max_length=127)),
                ('title', models.CharField(max_length=127)),
                ('brief', models.CharField(max_length=512)),
                ('play_count', models.IntegerField()),
                ('pub_time', models.IntegerField()),
            ],
        ),
    ]
