# Generated by Django 2.0.2 on 2018-03-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showscore', '0002_auto_20180315_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='brief',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='cover',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='play_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='pub_time',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
