# Generated by Django 2.0.2 on 2018-03-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showscore', '0003_auto_20180315_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='title',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
